### ISSUE TITLE
ValueError: setting an array element with a sequence. 

### ISSUE THREAD

**Issue by jamiejennings** [manzik/cmdbench#8]
I'm having a hard time getting `cmdbench` to work.  This problem manifests on macOS 14.4.1 and it appears when I replace the command I want to benchmark with 'sleep 1'.  And it happens also when I remove the single quotes around the command.

$ python3 --version
Python 3.12.4
$ cmdbench --version
cmdbench, version 0.1.20
$ echo $SHELL
/bin/bash
$ uname -v
Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
$ cmdbench -s -i 5 'sleep 1'
Benchmarking started..
  0%|                                                                                                      | 0/5 [00:00<?, ?it/s]0
Last runtime:  1.006 seconds:  20%|████████████▊                                                   | 1/5 [00:01<00:06,  1.56s/it]0
Last runtime:  1.006 seconds:  40%|█████████████████████████▌                                      | 2/5 [00:03<00:04,  1.59s/it]0
Last runtime:  1.006 seconds:  60%|██████████████████████████████████████▍                         | 3/5 [00:04<00:03,  1.57s/it]0
Last runtime:  1.006 seconds:  80%|███████████████████████████████████████████████████▏            | 4/5 [00:06<00:01,  1.56s/it]0
Last runtime:  1.005 seconds: 100%|████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.56s/it]
Benchmarking done.

Traceback (most recent call last):
  File "/opt/homebrew/bin/cmdbench", line 8, in <module>
    sys.exit(benchmark())
             ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/cli.py", line 96, in benchmark
    print_benchmark_dict(benchmark_results.get_statistics(), "Statistics")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/result.py", line 60, in get_statistics
    value_per_attribute_stats_dict = self._get_values_per_attribute(self.iterations, stats_replace_func)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/result.py", line 43, in _get_values_per_attribute
    value_per_attribute_dict[key] = self._get_values_per_attribute(list_of_objects_from_key, replace_func, key_path + [key])
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/result.py", line 43, in _get_values_per_attribute
    value_per_attribute_dict[key] = self._get_values_per_attribute(list_of_objects_from_key, replace_func, key_path + [key])
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/result.py", line 48, in _get_values_per_attribute
    values_list = replace_func(values_list, key_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/result.py", line 58, in stats_replace_func
    return BenchmarkStats(list_of_objects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/cmdbench/utils.py", line 68, in __init__
    data = np.array(data).flatten()
           ^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
$

**Comment by manzik** [comment]
Hey Jamie,
Sorry for the delay. This has been resolved in version 1.22 now: https://pypi.org/project/cmdbench/0.1.22/
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/d67d5c44-c9f5-49e3-8c39-ad0aee90969e">

**Comment by manzik** [comment]
@jamiejennings  Let me know if the issue has been resolved.

**Comment by manzik** [comment]
@jamiejennings Any update?

**Comment by jamiejennings** [comment]
Thank you, it is fixed!
